"""Kilo Code IDE generator.

Generates agent rule files with extended frontmatter and a .kilo.jsonc config.
"""

import logging

from project_flow.config import get_model_id
from project_flow.models import AgentKiloConfig, Artifact, FullConfig, TechStackData
from project_flow.utils import load_ide_paths
from project_flow.renderers.agents import render_agent_file

logger = logging.getLogger(__name__)


def generate(
    config: FullConfig, tech_stack: TechStackData, context: dict
) -> list[Artifact]:
    """Generate Kilo Code configuration files.

    Kilo generates:
    - Agent rule files with extended frontmatter (.kilo/files/{slug}.md)
    - A .kilo.jsonc configuration file listing all agents

    Args:
        config: The full configuration object.
        tech_stack: Parsed tech stack data.
        context: Template context dictionary.

    Returns:
        List of 15 Artifact objects: 14 agent files + 1 config file
    """
    artifacts = []

    if config.prompts:
        logger.warning(
            "Kilo does not support prompts. %d prompt(s) skipped.", len(config.prompts)
        )

    # Kilo-specific frontmatter fields (extended)
    ide_paths = load_ide_paths("kilo")
    kilo_frontmatter_fields = ide_paths.get(
        "frontmatter_fields",
        ["name", "description", "tools", "mode", "permission", "color", "model"],
    )

    # Generate agent files and collect config entries
    agent_configs = []

    for agent in config.agents:
        # Get model ID for this agent in Kilo context
        model_id = get_model_id(config, agent.slug, "kilo")

        # Render agent file with extended frontmatter
        content = render_agent_file(
            agent, model_id, kilo_frontmatter_fields, context, "kilo"
        )

        path = ide_paths["agent_file"].format(slug=agent.slug)
        artifacts.append(Artifact(path=path, content=content, source="kilo"))

        # Build agent entry for .kilo.jsonc config
        kilo_ide = config.ide_config.kilo
        color = (
            agent.kilo.color
            if agent.kilo.color != AgentKiloConfig.color
            else kilo_ide.default_color
        )
        mode = (
            agent.kilo.mode
            if agent.kilo.mode
            else (
                "primary"
                if agent.slug == kilo_ide.primary_agent
                else kilo_ide.default_mode
            )
        )
        agent_configs.append(
            {
                "slug": agent.slug,
                "name": agent.display_name,
                "description": agent.description,
                "model": model_id or agent.models.primary,
                "color": color,
                "mode": mode,
            }
        )

    # Generate .kilo.jsonc config file
    config_headers = ide_paths.get(
        "config_headers",
        ["// Kilo Code configuration", "// Auto-generated by project-flow"],
    )
    config_lines = list(config_headers) + [
        "{",
        '  "agents": [',
    ]

    for i, entry in enumerate(agent_configs):
        comma = "," if i < len(agent_configs) - 1 else ""
        config_lines.extend(
            [
                "    {",
                f'      "slug": "{entry["slug"]}",',
                f'      "name": "{entry["name"]}",',
                f'      "description": "{entry["description"]}",',
                f'      "model": "{entry["model"]}",',
                f'      "color": "{entry["color"]}",',
                f'      "mode": "{entry["mode"]}"',
                f"    }}{comma}",
            ]
        )

    config_lines.extend(
        [
            "  ]",
            "}",
        ]
    )

    config_content = "\n".join(config_lines)

    artifacts.append(
        Artifact(path=ide_paths["config_file"], content=config_content, source="kilo")
    )

    # Generate skill files for Kilo
    if config.skills:
        from project_flow.renderers.skills import render_skill_file, render_skills

        skills = render_skills(config.skills, context)
        for skill in skills:
            content = render_skill_file(skill)
            path = ide_paths["skill_file"].format(skill_name=skill["name"])
            artifacts.append(Artifact(path=path, content=content, source="kilo"))
    else:
        logger.info("No skills configured for Kilo.")

    return artifacts
