import json
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from project_flow import __version__
from project_flow.config import get_model_id, get_vscode_model_name
from project_flow.constants import JSON_INDENT, JSON_MERGE_MODE
from project_flow.utils import load_ide_paths
from project_flow.models import Artifact, FullConfig, TechStackData
from project_flow.renderers.agents import render_agent_file
from project_flow.renderers.rules import render_instructions
from project_flow.renderers.skills import render_skill_file, render_skills

_TEMPLATE_DIR = Path(__file__).parent.parent / "templates"
_ENV = Environment(
    loader=FileSystemLoader(str(_TEMPLATE_DIR)), keep_trailing_newline=True
)


def generate(
    config: FullConfig, tech_stack: TechStackData, context: dict
) -> list[Artifact]:
    """Generate all VS Code / GitHub Copilot artifacts. Returns a list of Artifact objects."""
    # Step 1: Initialize artifacts list
    artifacts = []

    # --- AGENT FILES (14 artifacts) ---
    # Step 2: Define VS Code frontmatter fields
    ide_paths = load_ide_paths("vscode")
    vscode_frontmatter_fields = ide_paths.get(
        "frontmatter_fields", ["name", "description", "tools", "handoffs"]
    )

    # Step 3: Generate agent files
    for agent in config.agents:
        # Step 3a: Get VS Code model picker name (e.g. "GPT-5.2 (copilot)")
        model_id = get_vscode_model_name(config, agent.slug)

        # Step 3b: Render agent file
        content = render_agent_file(
            agent, model_id, vscode_frontmatter_fields, context, "vscode"
        )

        # Step 3c: Determine file path
        path = ide_paths["agent_file"].format(slug=agent.slug)

        # Step 3d: Add artifact
        artifacts.append(Artifact(path=path, content=content, source="vscode"))

    # --- INSTRUCTIONS FILE (1 artifact) ---
    # Step 4: Render instructions
    instructions_content = render_instructions(tech_stack, context)

    # Step 5: Add instructions artifact
    artifacts.append(
        Artifact(
            path=ide_paths["instructions"],
            content=instructions_content,
            source="vscode",
        )
    )

    # --- SKILL FILES (from config.skills, dynamic count) ---
    # Step 6: Render skills
    skills = render_skills(config.skills, context)

    # Step 7: Generate skill files
    for skill in skills:
        # Step 7a: Render skill file content
        content = render_skill_file(skill)

        # Step 7b: Determine file path
        path = ide_paths["skill_file"].format(skill_name=skill["name"])

        # Step 7c: Add artifact
        artifacts.append(Artifact(path=path, content=content, source="vscode"))

    # --- PROMPT FILES (from config.prompts, dynamic count) ---
    # Step 8: Process prompt files
    for prompt in config.prompts:
        # Step 9a: Render prompt content with Jinja2, substituting variables and version
        rendered = _ENV.from_string(prompt.content).render(
            **context, version=__version__
        )

        # Step 9b: Add generated file header
        full_content = (
            f"<!-- Generated by project-flow v{__version__}. Do not edit directly. -->\n"
            + rendered
        )

        # Step 9c: Define file path
        path = ide_paths["prompt_file"].format(filename=prompt.filename)

        # Step 9d: Add artifact
        artifacts.append(Artifact(path=path, content=full_content, source="vscode"))

    # --- VS CODE SETTINGS (1 artifact, json_merge mode) ---
    # Step 10: Build settings dictionary using config-driven mode-to-agent mapping
    mode_agents = config.ide_config.vscode.mode_agents
    settings_keys = ide_paths.get("settings_keys", {})
    settings = {}
    if "ask_model" in settings_keys:
        settings[settings_keys["ask_model"]] = get_vscode_model_name(
            config, mode_agents.ask
        )
    if "edit_model" in settings_keys:
        settings[settings_keys["edit_model"]] = get_vscode_model_name(
            config, mode_agents.edit
        )
    if "agent_model" in settings_keys:
        settings[settings_keys["agent_model"]] = get_vscode_model_name(
            config, mode_agents.agent
        )

    # Step 11: Serialize settings to JSON
    json_string = json.dumps(settings, indent=JSON_INDENT)

    # Step 12: Add settings artifact with merge mode
    artifacts.append(
        Artifact(
            path=ide_paths["settings"],
            content=json_string,
            mode=JSON_MERGE_MODE,
            source="vscode",
        )
    )

    # --- UNIVERSAL AGENTS.md (1 artifact) ---
    # Generate AGENTS.md at project root for universal IDE compatibility
    agents_md_content = render_instructions(tech_stack, context)
    if "agents_md" in ide_paths:
        artifacts.append(
            Artifact(
                path=ide_paths["agents_md"],
                content=agents_md_content,
                source="vscode",
            )
        )

    # Step 13: Return all artifacts
    return artifacts
