"""Tests for renderer modules (agents, rules, skills)."""

from pathlib import Path

import pytest

from project_flow.models import (
    AgentConfig,
    AgentHandoff,
    AgentKiloConfig,
    AgentModels,
    FullConfig,
    SkillConfig,
    TechStackData,
)
from project_flow.renderers.agents import render_agent_file
from project_flow.renderers.rules import render_instructions
from project_flow.constants import UNKNOWN
from project_flow.renderers.skills import render_skill_file, render_skills


class TestAgentRenderer:
    """Test suite for agent file rendering."""

    def test_render_basic_agent(self) -> None:
        """Test rendering an agent with minimal configuration."""
        agent = AgentConfig(
            slug="test-agent",
            display_name="Test Agent",
            description="A test agent",
            prompt_file="agents/test.md",
            prompt_text="You are a test agent.",
            readonly=False,
            tools=["search/codebase", "edit"],
            models=AgentModels(
                primary="gpt-4", kilo_id="kilo/gpt-4", vscode_id="gpt-4"
            ),
            handoffs=[],
            kilo=AgentKiloConfig(color="gray"),
        )

        frontmatter_fields = ["name", "description", "tools"]
        context = {}
        result = render_agent_file(
            agent, "gpt-4", frontmatter_fields, context, "vscode"
        )

        assert "name: Test Agent" in result
        assert "description: A test agent" in result
        assert "- search/codebase" in result
        assert "- edit" in result
        assert "You are a test agent." in result
        assert "Generated by project-flow v0.1.0" in result

    def test_render_agent_with_handoffs(self) -> None:
        """Test rendering agent with handoff configuration."""
        agent = AgentConfig(
            slug="agent-a",
            display_name="Agent A",
            description="Agent with handoffs",
            prompt_file="agents/a.md",
            prompt_text="You are Agent A.",
            readonly=False,
            tools=["search/codebase"],
            models=AgentModels(
                primary="gpt-4", kilo_id="kilo/gpt-4", vscode_id="gpt-4"
            ),
            handoffs=[
                AgentHandoff(
                    label="Send to B", agent_slug="agent-b", send_immediately=False
                ),
                AgentHandoff(
                    label="Urgent to C", agent_slug="agent-c", send_immediately=True
                ),
            ],
            kilo=AgentKiloConfig(color="blue"),
        )

        frontmatter_fields = ["name", "description", "tools", "handoffs"]
        context = {
            "AVAILABLE_AGENTS": [
                {"slug": "agent-a", "display_name": "Agent A", "description": ""},
                {"slug": "agent-b", "display_name": "Agent B", "description": ""},
                {"slug": "agent-c", "display_name": "Agent C", "description": ""},
            ]
        }
        result = render_agent_file(
            agent, "gpt-4", frontmatter_fields, context, "vscode"
        )

        assert "handoffs:" in result
        assert "- label: Send to B" in result
        assert "agent: Agent B" in result
        assert "send: false" in result
        assert "- label: Urgent to C" in result
        assert "agent: Agent C" in result
        assert "send: true" in result

    def test_render_agent_omits_empty_handoffs(self) -> None:
        """Test that agents with no handoffs don't include handoffs in frontmatter."""
        agent = AgentConfig(
            slug="no-handoffs",
            display_name="No Handoffs",
            description="Agent without handoffs",
            prompt_file="agents/no.md",
            prompt_text="You have no handoffs.",
            readonly=True,
            tools=[],
            models=AgentModels(
                primary="gpt-4", kilo_id="kilo/gpt-4", vscode_id="gpt-4"
            ),
            handoffs=[],
            kilo=AgentKiloConfig(color="gray"),
        )

        frontmatter_fields = ["name", "description", "tools", "handoffs"]
        context = {}
        result = render_agent_file(
            agent, "gpt-4", frontmatter_fields, context, "vscode"
        )

        # Should not have handoffs section if empty
        assert "handoffs:" not in result
        assert "You have no handoffs." in result

    def test_render_agent_with_kilo_fields(self) -> None:
        """Test rendering agent with Kilo-specific frontmatter."""
        agent = AgentConfig(
            slug="kilo-agent",
            display_name="Kilo Agent",
            description="Agent with Kilo config",
            prompt_file="agents/kilo.md",
            prompt_text="You are a Kilo agent.",
            readonly=False,
            tools=["edit", "run/terminal"],
            models=AgentModels(
                primary="gpt-4", kilo_id="kilo/gpt-4", vscode_id="gpt-4"
            ),
            handoffs=[],
            kilo=AgentKiloConfig(color="red", mode="primary"),
        )

        frontmatter_fields = [
            "name",
            "description",
            "tools",
            "mode",
            "permission",
            "color",
        ]
        context = {}
        result = render_agent_file(agent, "gpt-4", frontmatter_fields, context, "kilo")

        assert "mode: primary" in result
        assert "permission: read,search,edit,shell" in result
        assert "color: red" in result

    def test_render_agent_with_globs(self) -> None:
        """Test rendering agent with language glob configuration."""
        agent = AgentConfig(
            slug="python-agent",
            display_name="Python Agent",
            description="Python specialist",
            prompt_file="agents/python.md",
            prompt_text="You are a Python expert.",
            readonly=False,
            tools=["search/codebase"],
            models=AgentModels(
                primary="gpt-4", kilo_id="kilo/gpt-4", vscode_id="gpt-4"
            ),
            handoffs=[],
            kilo=AgentKiloConfig(color="green"),
        )

        frontmatter_fields = ["name", "description", "globs"]
        context = {"LANGUAGE_GLOB": "**/*.py"}
        result = render_agent_file(
            agent, "gpt-4", frontmatter_fields, context, "cursor"
        )

        assert "globs:" in result
        assert "**/*.py" in result

    def test_render_agent_with_model_field(self) -> None:
        """Test rendering agent with model ID in frontmatter."""
        agent = AgentConfig(
            slug="model-agent",
            display_name="Model Agent",
            description="Agent with model config",
            prompt_file="agents/model.md",
            prompt_text="You use a specific model.",
            readonly=False,
            tools=["search/codebase"],
            models=AgentModels(
                primary="gpt-4", kilo_id="kilo/gpt-4", vscode_id="gpt-4"
            ),
            handoffs=[],
            kilo=AgentKiloConfig(color="blue"),
        )

        frontmatter_fields = ["name", "description", "model"]
        context = {}
        model_id = "custom-model-v2"
        result = render_agent_file(
            agent, model_id, frontmatter_fields, context, "vscode"
        )

        assert f"model: {model_id}" in result

    def test_render_agent_jinja2_substitution(self) -> None:
        """Test that agent prompt text undergoes Jinja2 template substitution."""
        agent = AgentConfig(
            slug="template-agent",
            display_name="Template Agent",
            description="Agent with template prompt",
            prompt_file="agents/template.md",
            prompt_text="You are working on {{ PROJECT_NAME }} using {{ TEST_FRAMEWORK }}.",
            readonly=False,
            tools=[],
            models=AgentModels(
                primary="gpt-4", kilo_id="kilo/gpt-4", vscode_id="gpt-4"
            ),
            handoffs=[],
            kilo=AgentKiloConfig(color="gray"),
        )

        frontmatter_fields = ["name"]
        context = {"PROJECT_NAME": "My Project", "TEST_FRAMEWORK": "pytest"}
        result = render_agent_file(
            agent, "gpt-4", frontmatter_fields, context, "vscode"
        )

        assert "You are working on My Project using pytest." in result
        assert "{{ PROJECT_NAME }}" not in result  # Should be substituted

    def test_render_agent_empty_frontmatter(self) -> None:
        """Test rendering agent with no frontmatter fields."""
        agent = AgentConfig(
            slug="simple-agent",
            display_name="Simple Agent",
            description="Simple",
            prompt_file="agents/simple.md",
            prompt_text="Simple prompt.",
            readonly=False,
            tools=[],
            models=AgentModels(
                primary="gpt-4", kilo_id="kilo/gpt-4", vscode_id="gpt-4"
            ),
            handoffs=[],
            kilo=AgentKiloConfig(color="gray"),
        )

        frontmatter_fields = []
        context = {}
        result = render_agent_file(
            agent, "gpt-4", frontmatter_fields, context, "vscode"
        )

        # Should not have YAML frontmatter delimiters
        assert "---" not in result[:100]
        assert "Simple prompt." in result
        assert "Generated by project-flow" in result


class TestRulesRenderer:
    """Test suite for instructions/rules rendering."""

    def test_render_basic_instructions(self) -> None:
        """Test rendering basic copilot instructions."""
        tech_stack = TechStackData(
            project_name="Test Project",
            project_description="A test project",
            primary_language="Python",
            global_coding_rules=["Use type hints", "Write docstrings"],
        )
        context = {
            "PROJECT_NAME": "Test Project",
            "PRIMARY_LANGUAGE": "Python",
            "FRAMEWORK": UNKNOWN,
            "DATABASE": UNKNOWN,
            "GLOBAL_CODING_RULES": ["Use type hints", "Write docstrings"],
            "PLANNING_DOCS": [],
        }

        result = render_instructions(tech_stack, context)

        assert "## Test Project Project-Specific Instructions" in result
        assert "Test Project" in result
        assert "Use type hints" in result
        assert "Write docstrings" in result

    def test_render_instructions_empty_tech_stack(self) -> None:
        """Test rendering with default tech stack data."""
        tech_stack = TechStackData()
        context = {
            "PROJECT_NAME": "Default Project",
            "PRIMARY_LANGUAGE": UNKNOWN,
            "FRAMEWORK": UNKNOWN,
            "DATABASE": UNKNOWN,
            "GLOBAL_CODING_RULES": [],
            "PLANNING_DOCS": [],
        }

        result = render_instructions(tech_stack, context)

        assert "## Default Project Project-Specific Instructions" in result
        assert "Default Project" in result

    def test_render_instructions_substitutes_variables(self) -> None:
        """Test that template variables are substituted in instructions."""
        tech_stack = TechStackData(
            project_name="Var Project",
            project_description="",
            primary_language="Go",
            framework="Gin",
            global_coding_rules=[],
        )
        context = {
            "PROJECT_NAME": "Var Project",
            "PRIMARY_LANGUAGE": "Go",
            "FRAMEWORK": "Gin",
            "DATABASE": UNKNOWN,
            "GLOBAL_CODING_RULES": [],
            "PLANNING_DOCS": [],
        }

        result = render_instructions(tech_stack, context)

        assert "Var Project" in result
        assert "Go" in result


class TestSkillsRenderer:
    """Test suite for skill file rendering."""

    def test_render_skill_file(self) -> None:
        """Test rendering a single skill file."""
        skill = {
            "name": "testing",
            "description": "Testing practices",
            "content": "# Testing Skill\n\nWrite comprehensive tests.",
        }

        result = render_skill_file(skill)

        assert "# Testing Skill" in result
        assert "Write comprehensive tests." in result
        assert "Generated by project-flow" in result

    def test_render_skills_with_jinja2_substitution(self) -> None:
        """Test that skill content undergoes template substitution."""
        skills_config = [
            SkillConfig(
                name="documentation",
                description="Doc standards",
                content="# Documentation\n\nYou are documenting {{ PROJECT_NAME }}.",
            )
        ]
        context = {"PROJECT_NAME": "My App"}

        result = render_skills(skills_config, context)

        assert len(result) == 1
        assert result[0]["name"] == "documentation"
        assert "You are documenting My App." in result[0]["content"]

    def test_render_multiple_skills(self) -> None:
        """Test rendering multiple skill configurations."""
        skills_config = [
            SkillConfig(
                name="testing",
                description="Test practices",
                content="# Testing\n\nTest everything.",
            ),
            SkillConfig(
                name="documentation",
                description="Doc standards",
                content="# Documentation\n\nDocument everything.",
            ),
        ]
        context = {}

        result = render_skills(skills_config, context)

        assert len(result) == 2
        assert result[0]["name"] == "testing"
        assert result[1]["name"] == "documentation"
        assert "# Testing" in result[0]["content"]
        assert "# Documentation" in result[1]["content"]

    def test_render_skills_empty_list(self) -> None:
        """Test rendering with no skills configured."""
        skills_config = []
        context = {}

        result = render_skills(skills_config, context)

        assert result == []

    def test_render_skill_with_multiline_content(self) -> None:
        """Test rendering skill with complex multiline content."""
        skill = {
            "name": "complex",
            "description": "Complex skill",
            "content": """# Complex Skill

## Guidelines

1. First rule
2. Second rule
3. Third rule

### Subsection
More details here.
""",
        }

        result = render_skill_file(skill)

        assert "# Complex Skill" in result
        assert "## Guidelines" in result
        assert "1. First rule" in result
        assert "### Subsection" in result
        assert "Generated by project-flow" in result

    def test_render_skill_preserves_yaml_special_chars(self) -> None:
        """Test that skills with YAML special characters render correctly."""
        skill = {
            "name": "yaml-safe",
            "description": "Skill with special chars",
            "content": """# YAML Safe Skill

- List item 1
- List item 2
- List with: colons

Value: 123
Nested:
  key: value
""",
        }

        result = render_skill_file(skill)

        assert "- List item 1" in result
        assert "- List with: colons" in result
        assert "Value: 123" in result
        assert "key: value" in result
