"""Central constants for Project Flow.

Single source of truth for all magic values, sentinels, defaults,
and configuration strings. No hardcoded values should exist elsewhere.
"""

# ---------------------------------------------------------------------------
# Version — single source; read from package metadata at runtime
# ---------------------------------------------------------------------------
try:
    from importlib.metadata import version as _pkg_version

    __version__ = _pkg_version("project-flow")
except Exception:
    __version__ = "0.1.0"

# ---------------------------------------------------------------------------
# Sentinel / defaults
# ---------------------------------------------------------------------------
UNKNOWN: str = "UNKNOWN"

# ---------------------------------------------------------------------------
# File I/O
# ---------------------------------------------------------------------------
DEFAULT_ENCODING: str = "utf-8"
JSON_INDENT: int = 2
JSON_MERGE_MODE: str = "json_merge"
DEFAULT_CONFIG_FILENAME: str = "project-flow.yml"
STAGING_PREFIX: str = "project-flow-staging-"
TIMESTAMP_FORMAT: str = "%Y%m%dT%H%M%S"
BACKUP_SUFFIX: str = ".bak."

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
CLI_PROG_NAME: str = "project-flow"
LOG_FORMAT_VERBOSE: str = "%(levelname)s: %(message)s"
LOG_FORMAT_QUIET: str = "%(levelname)s: %(message)s"
LOG_FORMAT_DEFAULT: str = "%(message)s"

# ---------------------------------------------------------------------------
# Defaults for project configuration
# ---------------------------------------------------------------------------
DEFAULT_OUTPUT_ROOT: str = "."
DEFAULT_KILO_COLOR: str = "gray"
DEFAULT_KILO_MODE: str = "subagent"
DEFAULT_PRIMARY_AGENT: str = "orchestrator"
DEFAULT_LANGUAGE_GLOB: str = "**/*"
DEFAULT_PROJECT_NAME: str = "my-project"
DEFAULT_PROJECT_DESCRIPTION: str = "Project scaffold generated by project-flow"

# Planning scaffold defaults
DEFAULT_PLAN_DIR: str = "docs/Plan"
DEFAULT_PLAN_PRD_FILE: str = "01-PRD.md"
DEFAULT_PLAN_ARCH_FILE: str = "02-ARCHITECTURE.md"
DEFAULT_PLAN_TECH_STACK_FILE: str = "03-TECH-STACK.md"
DEFAULT_PLAN_ADR_FILE: str = "04-ADR.md"
DEFAULT_PLAN_DATA_MODEL_FILE: str = "05-DATA-MODEL.md"
DEFAULT_PLAN_API_FILE: str = "06-API.md"
DEFAULT_PLAN_USER_FLOWS_FILE: str = "07-USER-FLOWS.md"
DEFAULT_PLAN_UI_SPEC_FILE: str = "08-UI-SPEC.md"
DEFAULT_PLAN_UX_SPEC_FILE: str = "09-UX-SPEC.md"
DEFAULT_PLAN_DEV_SETUP_FILE: str = "10-DEV-SETUP.md"
DEFAULT_PLAN_ENV_VARS_FILE: str = "11-ENV-VARS.md"
DEFAULT_PLAN_FOLDER_STRUCTURE_FILE: str = "12-FOLDER-STRUCTURE.md"
DEFAULT_PLAN_CONVENTIONS_FILE: str = "13-CONVENTIONS.md"
DEFAULT_PLAN_DEV_CHECKLIST_FILE: str = "14-DEV-CHECKLIST.json"
DEFAULT_PLAN_RUNBOOK_FILE: str = "15-RUNBOOK-DEPLOY.md"
DEFAULT_PLAN_INCIDENT_RESPONSE_FILE: str = "16-INCIDENT-RESPONSE.md"
DEFAULT_PLAN_MONITORING_FILE: str = "17-MONITORING.md"
DEFAULT_PLAN_KNOWN_ISSUES_FILE: str = "18-KNOWN-ISSUES.md"
DEFAULT_PLAN_GLOSSARY_FILE: str = "19-GLOSSARY.md"

# ---------------------------------------------------------------------------
# IDE names — single source of truth
# ---------------------------------------------------------------------------
SUPPORTED_IDES: list[str] = [
    "vscode",
    "kilo",
    "cursor",
    "windsurf",
    "zed",
    "void",
    "cline",
    "claude",
    "antigravity",
]

# ---------------------------------------------------------------------------
# Config schema
# ---------------------------------------------------------------------------
SUPPORTED_CONFIG_VERSIONS: list[str] = ["1.0"]
REQUIRED_CONFIG_KEYS: set[str] = {"version", "ides", "agents"}

# ---------------------------------------------------------------------------
# Tool-to-Kilo-permission mapping
# ---------------------------------------------------------------------------
TOOL_PERMISSION_MAP: dict[str, str] = {
    "edit": "edit",
    "run/terminal": "shell",
}
DEFAULT_KILO_PERMISSIONS: list[str] = ["read", "search"]

# ---------------------------------------------------------------------------
# Template file names
# ---------------------------------------------------------------------------
TEMPLATE_DIR_NAME: str = "templates"
AGENT_TEMPLATE: str = "agent.md.j2"
INSTRUCTIONS_TEMPLATE: str = "instructions.md.j2"
SKILL_TEMPLATE: str = "skill.md.j2"
CURSOR_RULE_TEMPLATE: str = "cursor_rule.mdc.j2"
